### ISSUE TITLE
Uploading file using Fetch.appendFile

### ISSUE THREAD

**Issue by ardave** [Zaid-Ajaj/Fable.SimpleHttp#15]
Using Fable.core 3.1.2 and Fable.SimpleHttp 2.6.  Am just trying to add a file upload button to a fable template site.

Using code like:
```
type Msg =
    | FileSelected of Browser.Types.File
    | FileUploadSuccess of unit
    | FileUploadError of exn
```
and the html is declared like:
```
input [ Type "file"
            OnChange (fun ev ->
               let target = ev.target
               let files = target?files
               let file = files?item(0)
               FileSelected file |> dispatch) ]
```
and 
```
let uploadFile (file:Browser.Types.File) = async {
    let formData =
        FormData.create()
        |> FormData.appendFile "file" file
    let! response =
        Http.request "/whatever"
        |> Http.method POST
        |> Http.content (BodyContent.Form formData)
        |> Http.send
    printfn "Status => %d" response.statusCode
}
```
(right or wrong, I got the "file" key name from the fetch documentation here https://github.com/github/fetch#file-upload)

and
```
let update (msg : Msg) (currentModel : Model) : Model * Cmd<Msg> =
    match currentModel.Counter, msg with
    | _, FileSelected file ->
        // Print some properties just to ensure we have indeed latched onto a File object:
        printfn "Selected: %A" file.name
        printfn "File size: %i" file.size
        let cmd = Cmd.OfAsync.either uploadFile file FileUploadSuccess FileUploadError
        currentModel, cmd
    | _, FileUploadSuccess () ->
        printfn "file upload success"
        currentModel, Cmd.none
    | _, FileUploadError ex ->
        printfn "Encountered an error like: %s" (ex.ToString())
        currentModel, Cmd.none**
    | _ -> currentModel, Cmd.none
```

and the console output I get is:

_New message: Object { tag: 2, name: "FileSelected", fields: (1) […] }
Selected: myFile.txt 
File size: 244 
Updated state:  Object { Counter: {…} }
New message: Object { tag: 4, name: "FileUploadError", fields: (1) […] }
Encountered an error like: 1_ 

... and I don't see how to troubleshoot further, given that the execution seems to "disappear into the framework," and then returns with an error "1".  

Any help that anyone has time to provide is greatly appreciated.

**Comment by Zaid-Ajaj** [comment]
Hello @ardave, 

It looks like that `uploadFile` somehow threw an exception which should never happen given that Http functions do not throw so this is strange. 

To troubleshoot this problem you need:
 - Call Browser.Dom.console.log(ex)` on the exception so that the entire stack trace is logged
 - Look at your "Network" to see whether the request actually went through to the server

In any case, I will be happy to look into it further if you can make a repository for me where this error occurs.

**Comment by ardave** [comment]
Thank you for responding.  I apologize for not initially including that I see no relevant traffic on the Network tab, aside from some GET requests to localhost:8000/socketcluster, which I have assumed are HMR-related traffic or something else not related to my file upload attempts.

Definitely no Network tab traffic to the /whatever endpoint that my code is intending to post to.

Browser.Dom.console.log(ex) just logs "1", as did printf'ing the exception.ToString()

I have put the code into a public repo, and the relevant code is here https://github.com/ardave/FileUpload/blob/master/src/Client/Client.fs

Thank you again,
Dave

**Comment by Zaid-Ajaj** [comment]
I will need to take a look at the full stack trace where this error is coming from. Will do that when I am back home after work :)

**Comment by Zaid-Ajaj** [comment]
The repository didn't even compile for me out of the box, I had to put `Fable.SimpleHttp` in the `Client` group in paket and updating fable-compiler using `yarn upgrade fable-compiler` and after that, the example works just fine without any changes in the code.

![2019_11_07_20_11_14_DevTools_localhost_8080_](https://user-images.githubusercontent.com/13316248/68419708-0f82a400-019b-11ea-8ccc-e05daf99c028.png)

**Comment by ardave** [comment]
While I have found myself referencing dependencies which do not seem version-compatible with each other, it is very likely that you have unblocked me with your help, which I greatly appreciate.
