### ISSUE TITLE
Request Method: DELETE is including undefined request payload

### ISSUE THREAD

**Issue by AlbertoDePena** [Zaid-Ajaj/Fable.SimpleHttp#43]
https://github.com/Zaid-Ajaj/Fable.SimpleHttp/blob/4f4a1a99a80b8084c11ba457d3f7e901d62ef663/src/Http.fs#L228

Should the code above include the DELETE verb as well?

Here is my code for reference...

```FSharp
let delete (id: Guid) =
    async {
        let! response =
            Http.request $"{Config.GetApiBaseAddress()}/api/v1/Users/{id}"
            |> Http.method DELETE
            |> Http.header (Headers.contentType "application/json")
            |> Http.header (Headers.authorization $"Bearer {AAD.getIdToken ()}")            
            |> Http.send

        let result =
            if response.statusCode = 204 then
                Ok()
            else
                response |> HttpResponse.tryParseAsApiMessage

        return result
    }
```

**Comment by AlbertoDePena** [comment]
Maybe instead of passing `None` to `xhr.Send`, it should pass `unit`...

Line 227

Change this

```FSharp
match req.method, req.content with
            | GET, _ -> xhr.send(None)
            | _, BodyContent.Empty -> xhr.send(None)
            | _, BodyContent.Text value -> xhr.send(value)
            | _, BodyContent.Form formData -> xhr.send(formData)
            | _, BodyContent.Binary blob -> xhr.send(blob)
```

to

```FSharp
match req.method, req.content with
            | GET, _ -> xhr.send()
            | _, BodyContent.Empty -> xhr.send()
            | _, BodyContent.Text value -> xhr.send(value)
            | _, BodyContent.Form formData -> xhr.send(formData)
            | _, BodyContent.Binary blob -> xhr.send(blob)
```

**Comment by Zaid-Ajaj** [comment]
@AlbertoDePena thanks for filing the issue, if you could send a PR that would be great! I think even GET or DELETE requests can have request payloads so no need to special case GET or DELETE 

> this issue is because Fable decided that `None` is `undefined` instead of `null` 


```fs
  match req.content with 
  | BodyContent.Empty -> xhr.send()
  | BodyContent.Text value -> xhr.send(value)
  | BodyContent.Form formData -> xhr.send(formData)
  | BodyContent.Binary blob -> xhr.send(blob)
```

**Comment by AlbertoDePena** [comment]
@Zaid-Ajaj 

Roget that! FYI, we use lots of your libraries since I have decided to do all things in FSharp for the applications I am responsible for. Anything I can do to help please let me know =)

**Comment by AlbertoDePena** [comment]
In case anyone is wondering... the issue surfaced when I placed my application behind Azure Front Door. One of the policies does not allow a request body on the DELETE HTTP verb...

**Comment by Zaid-Ajaj** [comment]
> Roget that! FYI, we use lots of your libraries since I have decided to do all things in FSharp for the applications I am responsible for. Anything I can do to help please let me know =)

I am glad my libraries are useful for you 🙏 

I've now merged and published the fix, it should be available as of Fable.SimpleHttp v3.2
