### ISSUE TITLE
Probably wrong 302 handling requests

### ISSUE THREAD

**Issue by d-arkhipenko** [Zaid-Ajaj/Fable.SimpleHttp#45]
Hi,

I'm trying to handle 302 redirects in Fable spa.
I've got a problem with GET request to server which returns 302 status code.

In my opinion this library doesn't handle this situation correctly :
https://github.com/Zaid-Ajaj/Fable.SimpleHttp/blob/17ab6a13746346f2a9f675663dcf55c4a2574fda/src/Http.fs#L175

Steps to reproduce:

1. Send to the sever any GET request
2. Receive from server 302 status with Location header
      |> Chrome will automatically send GET request by Location header and got 200 ok
3. This library will get response with 200 ok status and doesn't get 302 status with Location header.

Expected result:
Response with 302 status code and Location header

Probably I may use the Url from the latest 200 OK response and use it as Location header but I don't know how to do it, because `HttpResponse` type doesn't provide such information.
It will be nice to see the response with 302 status code and appropriate Location header inside.
If I've made some mistakes during using this library just push me in the right direction.

PS: 
In Elm [Http](https://package.elm-lang.org/packages/elm/http/latest/Http) library I've got the Location url inside `metadata.url`

<img width="1887" alt="http-fable-issue" src="https://user-images.githubusercontent.com/5019401/173222607-9b400dff-3578-441f-b8b1-05707f84ffcd.png">

Best regards.

**Comment by Zaid-Ajaj** [comment]
Hi @d-arkhipenko thanks for filing the issue! I have looked into it and I believe the resolution is for this library to expose [XHR.responseUrl](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL) from the response.

I will add that soon to HttpResponse

**Comment by Zaid-Ajaj** [comment]
Fixed in Fable.SimpleHttp v3.3 where `responseUrl` is now part of the `HttpResponse` type
