### ISSUE TITLE
.NET implementation

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Fable.SimpleHttp#6]
Would it be possible to provide a .Net implementation in parallel to Fable code using conditional compilation as Fable.React does? This would make it easier to create Type Providers compatible with Fable involving Http request, because you could use the same helpers in the TP and the quotations for generating code.

**Comment by Zaid-Ajaj** [comment]
Hello @alfonsogarciacaro, this is very interesting! although this library uses native browser APIs like `Blob` and `FormData` for the fully configurable requests, I think it would be possible to expose only the simple functions like `Http.get`, `Http.post` etc. from the dotnet side of things as well, maybe even a couple more variants that allow for sending and receiving request and response headers if needed, I guess this is what a TP needs in most common cases? 

> Sorry for the late answer, I must have marked it as read by mistake

**Comment by alfonsogarciacaro** [comment]
No, worries :) Yes, for the JSON providers and the like I guess GET and POST calls with JSON payloads should be enough.

**Comment by Zaid-Ajaj** [comment]
Hello @alfonsogarciacaro, I have made `Http.get` and `Http.post` variants that run on the dotnet side of things that have the same signature as those that run with Fable:
```fs
module Http = 

    open System.Net.Http
    open System.Net

    let get (url: string) : Async<int * string> =  
        async {
            use client = new HttpClient()
            let! response = Async.AwaitTask(client.GetAsync(url)) 
            let statusCode = int response.StatusCode
            let! responseBody = Async.AwaitTask(response.Content.ReadAsStringAsync())
            return statusCode, responseBody
        }

    let post (url: string) (data: string) : Async<int * string> = 
        async {
            use client = new HttpClient()
            let input = new StringContent(data, System.Text.Encoding.UTF8)
            let! response = Async.AwaitTask(client.PostAsync(url, input)) 
            let statusCode = int response.StatusCode
            let! responseBody = Async.AwaitTask(response.Content.ReadAsStringAsync())
            return statusCode, responseBody
        }
```
Can you please take it for a spin? Let me know how it goes ;)

**Comment by Zaid-Ajaj** [comment]
Seems to work if properly in a new *dotnet* console app:
```fs
// Learn more about F# at http://fsharp.org

open System
open Fable.SimpleHttp

let (status, content) = Async.RunSynchronously (Http.get "http://www.google.com")
printfn "Status %d and content: %s" status (content.Substring(0, 100))
```
Build and run
```bash
$ dotnet run
Status 200 and content: <!doctype html><html itemscope="" itemty
```

**Comment by alfonsogarciacaro** [comment]
Super-awesome, thank you! 🙇 https://twitter.com/FableCompiler/status/1128601197185835008
